# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b4562782cc50fb8634a314573a4f8ad91074d8c9b2c0ed1cc9f257f4648a21f64d823a632e59310c660045608635eee82bc35545448921ce5278f8cd742e28ad

test:
  secret_key_base: 59edf64918a9b26362a3350c76d3f6fa9eb092e5dde85e80a8abf11e99dbbf982c748bcf5e1433f1ae1eceaba59b8e2c319107e54cb6775d6bbd45eb5d9e9ddc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
